import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SideBar from "@/components/layout/SideBar";
import Header from "@/components/layout/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "InClass | Home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex justify-between items-start`}>
        <div className="min-w-[300px]   ">
          <SideBar /> 
        </div>
        <main className="w-full h-full ">
          <Header />
          {children}
        </main>
      </body>
    </html>
  );
}
